export const AGREEMENT_STATUSES = {
  NOT_GENERATED: 'NOT_GENERATED',
  DRAFT: 'DRAFT',
  READY_FOR_SIGNATURE: 'READY_FOR_SIGNATURE',
  ESIGN_INITIATED: 'ESIGN_INITIATED',
  ESIGN_PENDING: 'ESIGN_PENDING',
  ESIGN_SUCCESS: 'ESIGN_SUCCESS',
  VERIFICATION_PENDING: 'VERIFICATION_PENDING',
  SIGNED: 'SIGNED',
  SANDBOX_SIGNED: 'SANDBOX_SIGNED',
  ESIGN_FAILED: 'ESIGN_FAILED',
  ESIGN_CANCELLED: 'ESIGN_CANCELLED',
  EXPIRED: 'EXPIRED',
  VOID: 'VOID',
  SUPERSEDED: 'SUPERSEDED',
} as const;

export const AGREEMENT_EVENTS = {
  GENERATED: 'AGREEMENT_GENERATED',
  VIEWED: 'AGREEMENT_VIEWED',
  CONSENT_ACCEPTED: 'CONSENT_ACCEPTED',
  ESIGN_INITIATED: 'ESIGN_INITIATED',
  ESIGN_REDIRECTED: 'ESIGN_REDIRECTED',
  CALLBACK_RECEIVED: 'ESIGN_CALLBACK_RECEIVED',
  VERIFIED: 'ESIGN_VERIFIED',
  SIGNED: 'AGREEMENT_SIGNED',
  FAILED: 'ESIGN_FAILED',
  RETRIED: 'ESIGN_RETRIED',
  VOIDED: 'AGREEMENT_VOIDED',
  SUPERSEDED: 'AGREEMENT_SUPERSEDED',
} as const;

export const RETRYABLE_STATUSES = [
  AGREEMENT_STATUSES.READY_FOR_SIGNATURE,
  AGREEMENT_STATUSES.ESIGN_FAILED,
  AGREEMENT_STATUSES.ESIGN_CANCELLED,
  AGREEMENT_STATUSES.EXPIRED,
] as string[];

export const ACTIVE_TRANSACTION_STATUSES = [
  AGREEMENT_STATUSES.ESIGN_INITIATED,
  AGREEMENT_STATUSES.ESIGN_PENDING,
  AGREEMENT_STATUSES.ESIGN_SUCCESS,
  AGREEMENT_STATUSES.VERIFICATION_PENDING,
] as string[];
